default: &default
  access_key_id: "AKIAIJI2KSX7HZWGBOBQ"
  secret_access_key: "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"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
